function [ V ] = velocity(X, V, S, G, I, params, dir, D)
    if(dir == 1)
        V = params.IW * V + dir * (...
            I * params.SC * rand * (G.X - X) + ...
            (I - 1) * params.GC * rand * S);
    else
%         V = params.IW * V + dir * (...
%             I * params.SC * rand(1, D) .* (G.X - X) + ...
%             (I - 1) * params.GC * rand(1, D) .* S);

        M1 = m_function(params);
        V = params.IW * V + dir * (...
            I * params.SC * rand * (M1 * (G.X - X)')' + ...
            (I - 1) * params.GC * rand * (M1 * S')');   
        
    end
end
